services:
  - type: web
    name: joker3k-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python render_webhook_bot.py
    autoDeploy: true
    envVars:
      - key: TOKEN
        value: __TON_TOKEN_TELEGRAM_ICI__
      - key: WEBHOOK_URL
        value: https://joker3k-bot.onrender.com/webhook
      - key: DATABASE_URL
        fromDatabase:
          name: joker3k-db
          property: connectionString

databases:
  - name: joker3k-db
    plan: free
    region: frankfurt
